/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *acceuil;
    QPushButton *adherant;
    QPushButton *logistique;
    QPushButton *famille;
    QPushButton *finance;
    QPushButton *physiques;
    QWidget *adherant_2;
    QPushButton *retour_adherant;
    QPushButton *adherant_4;
    QPushButton *adherant_5;
    QWidget *adherant_3;
    QPushButton *retour_adherant_3;
    QToolBox *toolBox_4;
    QWidget *page_10;
    QTableWidget *tableWidget_7;
    QGroupBox *groupBox_7;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_30;
    QWidget *simplemembre;
    QToolBox *toolBox_5;
    QWidget *page_11;
    QTableWidget *tableWidget_8;
    QGroupBox *groupBox_8;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *retour_adherant_2;
    QWidget *famille_2;
    QLabel *label_2;
    QPushButton *retour_famille;
    QWidget *finance_2;
    QPushButton *retour_finance;
    QToolBox *toolBox_2;
    QWidget *page_4;
    QTableWidget *tableWidget_3;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_13;
    QWidget *page_5;
    QTableWidget *tableWidget_4;
    QGroupBox *groupBox_4;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QWidget *page_6;
    QGraphicsView *graphicsView_2;
    QWidget *logistique_2;
    QPushButton *retour_logistique;
    QToolBox *toolBox;
    QWidget *page;
    QTableWidget *tableWidget;
    QGroupBox *groupBox;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QWidget *page_2;
    QTableWidget *tableWidget_2;
    QGroupBox *groupBox_2;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QWidget *page_3;
    QGraphicsView *graphicsView;
    QWidget *physique;
    QPushButton *retour_physique;
    QToolBox *toolBox_3;
    QWidget *page_7;
    QTableWidget *tableWidget_5;
    QGroupBox *groupBox_5;
    QPushButton *pushButton_14;
    QWidget *page_8;
    QTableWidget *tableWidget_6;
    QGroupBox *groupBox_6;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QWidget *page_9;
    QGraphicsView *graphicsView_3;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1198, 718);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        centralwidget->setStyleSheet(QStringLiteral(""));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(20, 10, 1151, 681));
        stackedWidget->setStyleSheet(QStringLiteral("background-color: rgb(89, 97, 255);"));
        acceuil = new QWidget();
        acceuil->setObjectName(QStringLiteral("acceuil"));
        acceuil->setStyleSheet(QStringLiteral(""));
        adherant = new QPushButton(acceuil);
        adherant->setObjectName(QStringLiteral("adherant"));
        adherant->setGeometry(QRect(480, 310, 161, 28));
        adherant->setStyleSheet(QStringLiteral("font: 10pt \"Poor Richard\";"));
        logistique = new QPushButton(acceuil);
        logistique->setObjectName(QStringLiteral("logistique"));
        logistique->setGeometry(QRect(90, 540, 191, 28));
        logistique->setStyleSheet(QStringLiteral("font: 10pt \"Poor Richard\";"));
        famille = new QPushButton(acceuil);
        famille->setObjectName(QStringLiteral("famille"));
        famille->setGeometry(QRect(70, 100, 151, 28));
        famille->setStyleSheet(QStringLiteral("font: 10pt \"Poor Richard\";"));
        finance = new QPushButton(acceuil);
        finance->setObjectName(QStringLiteral("finance"));
        finance->setGeometry(QRect(870, 100, 221, 28));
        finance->setStyleSheet(QStringLiteral("font: 10pt \"Poor Richard\";"));
        physiques = new QPushButton(acceuil);
        physiques->setObjectName(QStringLiteral("physiques"));
        physiques->setGeometry(QRect(860, 530, 211, 28));
        physiques->setStyleSheet(QStringLiteral("font: 10pt \"Poor Richard\";"));
        stackedWidget->addWidget(acceuil);
        adherant_2 = new QWidget();
        adherant_2->setObjectName(QStringLiteral("adherant_2"));
        retour_adherant = new QPushButton(adherant_2);
        retour_adherant->setObjectName(QStringLiteral("retour_adherant"));
        retour_adherant->setGeometry(QRect(1050, 620, 93, 28));
        adherant_4 = new QPushButton(adherant_2);
        adherant_4->setObjectName(QStringLiteral("adherant_4"));
        adherant_4->setGeometry(QRect(430, 230, 191, 28));
        adherant_5 = new QPushButton(adherant_2);
        adherant_5->setObjectName(QStringLiteral("adherant_5"));
        adherant_5->setGeometry(QRect(430, 300, 191, 28));
        stackedWidget->addWidget(adherant_2);
        adherant_3 = new QWidget();
        adherant_3->setObjectName(QStringLiteral("adherant_3"));
        adherant_3->setEnabled(true);
        retour_adherant_3 = new QPushButton(adherant_3);
        retour_adherant_3->setObjectName(QStringLiteral("retour_adherant_3"));
        retour_adherant_3->setGeometry(QRect(1040, 610, 93, 28));
        toolBox_4 = new QToolBox(adherant_3);
        toolBox_4->setObjectName(QStringLiteral("toolBox_4"));
        toolBox_4->setGeometry(QRect(70, 100, 971, 451));
        toolBox_4->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        page_10 = new QWidget();
        page_10->setObjectName(QStringLiteral("page_10"));
        page_10->setGeometry(QRect(0, 0, 971, 421));
        tableWidget_7 = new QTableWidget(page_10);
        if (tableWidget_7->columnCount() < 7)
            tableWidget_7->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        tableWidget_7->setObjectName(QStringLiteral("tableWidget_7"));
        tableWidget_7->setGeometry(QRect(50, 20, 711, 311));
        tableWidget_7->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        groupBox_7 = new QGroupBox(page_10);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(810, 10, 161, 321));
        pushButton_15 = new QPushButton(groupBox_7);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(10, 30, 141, 28));
        QIcon icon;
        icon.addFile(QStringLiteral("../../Downloads/icons8-add-user-male-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_15->setIcon(icon);
        pushButton_16 = new QPushButton(groupBox_7);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(10, 80, 141, 28));
        QIcon icon1;
        icon1.addFile(QStringLiteral("../../Downloads/icons8-registration-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_16->setIcon(icon1);
        pushButton_17 = new QPushButton(groupBox_7);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(10, 130, 141, 28));
        QIcon icon2;
        icon2.addFile(QStringLiteral("../../Downloads/icons8-denied-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_17->setIcon(icon2);
        pushButton_18 = new QPushButton(groupBox_7);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(10, 180, 141, 28));
        QIcon icon3;
        icon3.addFile(QStringLiteral("../../Downloads/icons8-print-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_18->setIcon(icon3);
        pushButton_19 = new QPushButton(groupBox_7);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(10, 230, 141, 28));
        QIcon icon4;
        icon4.addFile(QStringLiteral("../../Downloads/icons8-search-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_19->setIcon(icon4);
        pushButton_30 = new QPushButton(groupBox_7);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(10, 280, 141, 28));
        QIcon icon5;
        icon5.addFile(QStringLiteral("../../Downloads/icons8-location-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_30->setIcon(icon5);
        QIcon icon6;
        icon6.addFile(QStringLiteral("../../Downloads/icons8-fournisseur-100.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolBox_4->addItem(page_10, icon6, QStringLiteral("Gestion des adherants"));
        stackedWidget->addWidget(adherant_3);
        simplemembre = new QWidget();
        simplemembre->setObjectName(QStringLiteral("simplemembre"));
        toolBox_5 = new QToolBox(simplemembre);
        toolBox_5->setObjectName(QStringLiteral("toolBox_5"));
        toolBox_5->setGeometry(QRect(100, 110, 971, 451));
        toolBox_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        page_11 = new QWidget();
        page_11->setObjectName(QStringLiteral("page_11"));
        page_11->setGeometry(QRect(0, 0, 971, 421));
        tableWidget_8 = new QTableWidget(page_11);
        if (tableWidget_8->columnCount() < 7)
            tableWidget_8->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(2, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(3, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(4, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(5, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(6, __qtablewidgetitem13);
        tableWidget_8->setObjectName(QStringLiteral("tableWidget_8"));
        tableWidget_8->setGeometry(QRect(50, 20, 711, 311));
        tableWidget_8->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        groupBox_8 = new QGroupBox(page_11);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(810, 10, 161, 321));
        pushButton_31 = new QPushButton(groupBox_8);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(10, 30, 141, 28));
        pushButton_31->setIcon(icon);
        pushButton_32 = new QPushButton(groupBox_8);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(10, 80, 141, 28));
        pushButton_32->setIcon(icon1);
        pushButton_33 = new QPushButton(groupBox_8);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(10, 130, 141, 28));
        pushButton_33->setIcon(icon2);
        pushButton_34 = new QPushButton(groupBox_8);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(10, 180, 141, 28));
        pushButton_34->setIcon(icon3);
        pushButton_35 = new QPushButton(groupBox_8);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(10, 230, 141, 28));
        pushButton_35->setIcon(icon4);
        pushButton_36 = new QPushButton(groupBox_8);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(10, 280, 141, 28));
        pushButton_36->setIcon(icon5);
        toolBox_5->addItem(page_11, icon6, QStringLiteral("Gestion des simple membres"));
        retour_adherant_2 = new QPushButton(simplemembre);
        retour_adherant_2->setObjectName(QStringLiteral("retour_adherant_2"));
        retour_adherant_2->setGeometry(QRect(1040, 620, 93, 28));
        stackedWidget->addWidget(simplemembre);
        famille_2 = new QWidget();
        famille_2->setObjectName(QStringLiteral("famille_2"));
        label_2 = new QLabel(famille_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(290, 220, 56, 16));
        retour_famille = new QPushButton(famille_2);
        retour_famille->setObjectName(QStringLiteral("retour_famille"));
        retour_famille->setGeometry(QRect(650, 500, 93, 28));
        stackedWidget->addWidget(famille_2);
        finance_2 = new QWidget();
        finance_2->setObjectName(QStringLiteral("finance_2"));
        retour_finance = new QPushButton(finance_2);
        retour_finance->setObjectName(QStringLiteral("retour_finance"));
        retour_finance->setGeometry(QRect(1050, 640, 93, 28));
        toolBox_2 = new QToolBox(finance_2);
        toolBox_2->setObjectName(QStringLiteral("toolBox_2"));
        toolBox_2->setGeometry(QRect(120, 120, 971, 451));
        toolBox_2->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        page_4->setGeometry(QRect(0, 0, 100, 30));
        tableWidget_3 = new QTableWidget(page_4);
        if (tableWidget_3->columnCount() < 4)
            tableWidget_3->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(1, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(2, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(3, __qtablewidgetitem17);
        tableWidget_3->setObjectName(QStringLiteral("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(50, 20, 711, 311));
        tableWidget_3->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        groupBox_3 = new QGroupBox(page_4);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(810, 10, 161, 321));
        pushButton_13 = new QPushButton(groupBox_3);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(0, 130, 141, 28));
        pushButton_13->setIcon(icon);
        toolBox_2->addItem(page_4, icon6, QStringLiteral("Ajouter dons financiers"));
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        page_5->setGeometry(QRect(0, 0, 971, 361));
        tableWidget_4 = new QTableWidget(page_5);
        if (tableWidget_4->columnCount() < 4)
            tableWidget_4->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(0, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(1, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(2, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(3, __qtablewidgetitem21);
        tableWidget_4->setObjectName(QStringLiteral("tableWidget_4"));
        tableWidget_4->setGeometry(QRect(10, 30, 761, 311));
        groupBox_4 = new QGroupBox(page_5);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(800, 20, 161, 321));
        pushButton_20 = new QPushButton(groupBox_4);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(10, 80, 141, 28));
        pushButton_20->setIcon(icon1);
        pushButton_21 = new QPushButton(groupBox_4);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(10, 130, 141, 28));
        QIcon icon7;
        icon7.addFile(QStringLiteral("../../Downloads/icons8-data-backup-64.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_21->setIcon(icon7);
        pushButton_22 = new QPushButton(groupBox_4);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(10, 180, 141, 28));
        pushButton_22->setIcon(icon3);
        pushButton_23 = new QPushButton(groupBox_4);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(10, 230, 141, 28));
        pushButton_23->setIcon(icon4);
        pushButton_24 = new QPushButton(groupBox_4);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(10, 280, 141, 28));
        pushButton_24->setIcon(icon5);
        QIcon icon8;
        icon8.addFile(QStringLiteral("../../Downloads/icons8-livraison-de-nourriture-100 (1).png"), QSize(), QIcon::Normal, QIcon::Off);
        toolBox_2->addItem(page_5, icon8, QStringLiteral("afficher dons financiers"));
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        page_6->setGeometry(QRect(0, 0, 100, 30));
        graphicsView_2 = new QGraphicsView(page_6);
        graphicsView_2->setObjectName(QStringLiteral("graphicsView_2"));
        graphicsView_2->setGeometry(QRect(20, 0, 951, 341));
        toolBox_2->addItem(page_6, icon5, QStringLiteral("statistiques"));
        stackedWidget->addWidget(finance_2);
        logistique_2 = new QWidget();
        logistique_2->setObjectName(QStringLiteral("logistique_2"));
        retour_logistique = new QPushButton(logistique_2);
        retour_logistique->setObjectName(QStringLiteral("retour_logistique"));
        retour_logistique->setGeometry(QRect(1030, 540, 93, 28));
        toolBox = new QToolBox(logistique_2);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setGeometry(QRect(70, 50, 971, 451));
        toolBox->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        page->setGeometry(QRect(0, 0, 971, 361));
        tableWidget = new QTableWidget(page);
        if (tableWidget->columnCount() < 7)
            tableWidget->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(4, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(5, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(6, __qtablewidgetitem28);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(50, 20, 711, 311));
        tableWidget->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        groupBox = new QGroupBox(page);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(810, 10, 161, 321));
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 30, 141, 28));
        pushButton->setIcon(icon);
        pushButton_2 = new QPushButton(groupBox);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 80, 141, 28));
        pushButton_2->setIcon(icon1);
        pushButton_3 = new QPushButton(groupBox);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(10, 130, 141, 28));
        pushButton_3->setIcon(icon2);
        pushButton_4 = new QPushButton(groupBox);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(10, 180, 141, 28));
        pushButton_4->setIcon(icon3);
        pushButton_5 = new QPushButton(groupBox);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(10, 230, 141, 28));
        pushButton_5->setIcon(icon4);
        pushButton_6 = new QPushButton(groupBox);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(10, 280, 141, 28));
        pushButton_6->setIcon(icon5);
        toolBox->addItem(page, icon6, QStringLiteral("Gestion Livreurs"));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 100, 30));
        tableWidget_2 = new QTableWidget(page_2);
        if (tableWidget_2->columnCount() < 7)
            tableWidget_2->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(1, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(2, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(3, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(4, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(5, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(6, __qtablewidgetitem35);
        tableWidget_2->setObjectName(QStringLiteral("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(10, 30, 761, 311));
        groupBox_2 = new QGroupBox(page_2);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(800, 20, 161, 321));
        pushButton_7 = new QPushButton(groupBox_2);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(10, 30, 141, 28));
        QIcon icon9;
        icon9.addFile(QStringLiteral("../../Downloads/icons8-view-64.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_7->setIcon(icon9);
        pushButton_8 = new QPushButton(groupBox_2);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(10, 80, 141, 28));
        pushButton_8->setIcon(icon1);
        pushButton_9 = new QPushButton(groupBox_2);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(10, 130, 141, 28));
        pushButton_9->setIcon(icon7);
        pushButton_10 = new QPushButton(groupBox_2);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(10, 180, 141, 28));
        pushButton_10->setIcon(icon3);
        pushButton_11 = new QPushButton(groupBox_2);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(10, 230, 141, 28));
        pushButton_11->setIcon(icon4);
        pushButton_12 = new QPushButton(groupBox_2);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(10, 280, 141, 28));
        pushButton_12->setIcon(icon5);
        toolBox->addItem(page_2, icon8, QStringLiteral("Bon de Livraisons"));
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        page_3->setGeometry(QRect(0, 0, 100, 30));
        graphicsView = new QGraphicsView(page_3);
        graphicsView->setObjectName(QStringLiteral("graphicsView"));
        graphicsView->setGeometry(QRect(20, 0, 951, 341));
        toolBox->addItem(page_3, icon5, QStringLiteral("Localisation"));
        stackedWidget->addWidget(logistique_2);
        physique = new QWidget();
        physique->setObjectName(QStringLiteral("physique"));
        retour_physique = new QPushButton(physique);
        retour_physique->setObjectName(QStringLiteral("retour_physique"));
        retour_physique->setGeometry(QRect(1060, 630, 93, 28));
        toolBox_3 = new QToolBox(physique);
        toolBox_3->setObjectName(QStringLiteral("toolBox_3"));
        toolBox_3->setGeometry(QRect(120, 90, 971, 451));
        toolBox_3->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        page_7->setGeometry(QRect(0, 0, 971, 361));
        tableWidget_5 = new QTableWidget(page_7);
        if (tableWidget_5->columnCount() < 4)
            tableWidget_5->setColumnCount(4);
        QFont font;
        font.setPointSize(12);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        __qtablewidgetitem36->setFont(font);
        tableWidget_5->setHorizontalHeaderItem(0, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget_5->setHorizontalHeaderItem(1, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget_5->setHorizontalHeaderItem(2, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget_5->setHorizontalHeaderItem(3, __qtablewidgetitem39);
        tableWidget_5->setObjectName(QStringLiteral("tableWidget_5"));
        tableWidget_5->setGeometry(QRect(50, 20, 711, 311));
        tableWidget_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));
        groupBox_5 = new QGroupBox(page_7);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(810, 10, 161, 321));
        pushButton_14 = new QPushButton(groupBox_5);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(0, 130, 141, 28));
        pushButton_14->setIcon(icon);
        toolBox_3->addItem(page_7, icon6, QStringLiteral("Ajouter stock"));
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        page_8->setGeometry(QRect(0, 0, 971, 361));
        tableWidget_6 = new QTableWidget(page_8);
        if (tableWidget_6->columnCount() < 4)
            tableWidget_6->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(0, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(1, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(2, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(3, __qtablewidgetitem43);
        tableWidget_6->setObjectName(QStringLiteral("tableWidget_6"));
        tableWidget_6->setGeometry(QRect(10, 30, 761, 311));
        groupBox_6 = new QGroupBox(page_8);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(800, 20, 161, 321));
        pushButton_25 = new QPushButton(groupBox_6);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(10, 80, 141, 28));
        pushButton_25->setIcon(icon1);
        pushButton_26 = new QPushButton(groupBox_6);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(10, 130, 141, 28));
        pushButton_26->setIcon(icon7);
        pushButton_27 = new QPushButton(groupBox_6);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(10, 180, 141, 28));
        pushButton_27->setIcon(icon3);
        pushButton_28 = new QPushButton(groupBox_6);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(10, 230, 141, 28));
        pushButton_28->setIcon(icon4);
        pushButton_29 = new QPushButton(groupBox_6);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(10, 280, 141, 28));
        pushButton_29->setIcon(icon5);
        toolBox_3->addItem(page_8, icon8, QStringLiteral("afficher stock"));
        page_9 = new QWidget();
        page_9->setObjectName(QStringLiteral("page_9"));
        page_9->setGeometry(QRect(0, 0, 971, 361));
        graphicsView_3 = new QGraphicsView(page_9);
        graphicsView_3->setObjectName(QStringLiteral("graphicsView_3"));
        graphicsView_3->setGeometry(QRect(20, 0, 951, 341));
        toolBox_3->addItem(page_9, icon5, QStringLiteral("statistiques"));
        stackedWidget->addWidget(physique);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1198, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(2);
        toolBox_4->setCurrentIndex(0);
        toolBox_5->setCurrentIndex(0);
        toolBox_2->setCurrentIndex(1);
        toolBox->setCurrentIndex(0);
        toolBox_3->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        adherant->setText(QApplication::translate("MainWindow", "GESTION ADHERANT", Q_NULLPTR));
        logistique->setText(QApplication::translate("MainWindow", "GESTION LOGISTIQUE", Q_NULLPTR));
        famille->setText(QApplication::translate("MainWindow", "GESTION FAMILLE", Q_NULLPTR));
        finance->setText(QApplication::translate("MainWindow", "GESTION DONS FINANCIERS", Q_NULLPTR));
        physiques->setText(QApplication::translate("MainWindow", "GESTION DONS PHYSIQUES", Q_NULLPTR));
        retour_adherant->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        adherant_4->setText(QApplication::translate("MainWindow", "Adherant", Q_NULLPTR));
        adherant_5->setText(QApplication::translate("MainWindow", "simple membre", Q_NULLPTR));
        retour_adherant_3->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_7->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_7->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_7->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_7->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_7->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget_7->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "Ville", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_7->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", "importer image", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "Nouveaux", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("MainWindow", "Generer PDF", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_30->setText(QApplication::translate("MainWindow", "Localiser", Q_NULLPTR));
        toolBox_4->setItemText(toolBox_4->indexOf(page_10), QApplication::translate("MainWindow", "Gestion des adherants", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_8->horizontalHeaderItem(0);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_8->horizontalHeaderItem(1);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_8->horizontalHeaderItem(2);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_8->horizontalHeaderItem(3);
        ___qtablewidgetitem10->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_8->horizontalHeaderItem(4);
        ___qtablewidgetitem11->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_8->horizontalHeaderItem(5);
        ___qtablewidgetitem12->setText(QApplication::translate("MainWindow", "Ville", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_8->horizontalHeaderItem(6);
        ___qtablewidgetitem13->setText(QApplication::translate("MainWindow", "importer image", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_31->setText(QApplication::translate("MainWindow", "Nouveaux", Q_NULLPTR));
        pushButton_32->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        pushButton_33->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        pushButton_34->setText(QApplication::translate("MainWindow", "Imprimer PDF", Q_NULLPTR));
        pushButton_35->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_36->setText(QApplication::translate("MainWindow", "Localiser", Q_NULLPTR));
        toolBox_5->setItemText(toolBox_5->indexOf(page_11), QApplication::translate("MainWindow", "Gestion des simple membres", Q_NULLPTR));
        retour_adherant_2->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "fammille", Q_NULLPTR));
        retour_famille->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        retour_finance->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_3->horizontalHeaderItem(0);
        ___qtablewidgetitem14->setText(QApplication::translate("MainWindow", "ID ", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_3->horizontalHeaderItem(1);
        ___qtablewidgetitem15->setText(QApplication::translate("MainWindow", "Nom doneurs", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_3->horizontalHeaderItem(2);
        ___qtablewidgetitem16->setText(QApplication::translate("MainWindow", "somme", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_3->horizontalHeaderItem(3);
        ___qtablewidgetitem17->setText(QApplication::translate("MainWindow", "date", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "Nouveaux", Q_NULLPTR));
        toolBox_2->setItemText(toolBox_2->indexOf(page_4), QApplication::translate("MainWindow", "Ajouter dons financiers", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_4->horizontalHeaderItem(0);
        ___qtablewidgetitem18->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_4->horizontalHeaderItem(1);
        ___qtablewidgetitem19->setText(QApplication::translate("MainWindow", "Nom Doneurs", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_4->horizontalHeaderItem(2);
        ___qtablewidgetitem20->setText(QApplication::translate("MainWindow", "somme", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_4->horizontalHeaderItem(3);
        ___qtablewidgetitem21->setText(QApplication::translate("MainWindow", "Date", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        pushButton_21->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("MainWindow", "fichier exel", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_24->setText(QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        toolBox_2->setItemText(toolBox_2->indexOf(page_5), QApplication::translate("MainWindow", "afficher dons financiers", Q_NULLPTR));
        toolBox_2->setItemText(toolBox_2->indexOf(page_6), QApplication::translate("MainWindow", "statistiques", Q_NULLPTR));
        retour_logistique->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem22->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem23->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem24->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem25->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->horizontalHeaderItem(4);
        ___qtablewidgetitem26->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget->horizontalHeaderItem(5);
        ___qtablewidgetitem27->setText(QApplication::translate("MainWindow", "Ville", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget->horizontalHeaderItem(6);
        ___qtablewidgetitem28->setText(QApplication::translate("MainWindow", "Code Postal", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "Nouveaux", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "Imprimer PDF", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("MainWindow", "Localiser", Q_NULLPTR));
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Gestion Livreurs", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem29->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_2->horizontalHeaderItem(1);
        ___qtablewidgetitem30->setText(QApplication::translate("MainWindow", "Nom Famille", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_2->horizontalHeaderItem(2);
        ___qtablewidgetitem31->setText(QApplication::translate("MainWindow", "Livereur", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_2->horizontalHeaderItem(3);
        ___qtablewidgetitem32->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone Famille", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_2->horizontalHeaderItem(4);
        ___qtablewidgetitem33->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_2->horizontalHeaderItem(5);
        ___qtablewidgetitem34->setText(QApplication::translate("MainWindow", "Ville", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_2->horizontalHeaderItem(6);
        ___qtablewidgetitem35->setText(QApplication::translate("MainWindow", "Code Postal", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("MainWindow", "D\303\251tails", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("MainWindow", "Affectter", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "Archiver", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("MainWindow", "Imprimer PDF", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "Localiser", Q_NULLPTR));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "Bon de Livraisons", Q_NULLPTR));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "Localisation", Q_NULLPTR));
        retour_physique->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_5->horizontalHeaderItem(0);
        ___qtablewidgetitem36->setText(QApplication::translate("MainWindow", "numero ", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_5->horizontalHeaderItem(1);
        ___qtablewidgetitem37->setText(QApplication::translate("MainWindow", "quantite", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_5->horizontalHeaderItem(2);
        ___qtablewidgetitem38->setText(QApplication::translate("MainWindow", "libelle", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_5->horizontalHeaderItem(3);
        ___qtablewidgetitem39->setText(QApplication::translate("MainWindow", "date", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("MainWindow", "Nouveaux", Q_NULLPTR));
        toolBox_3->setItemText(toolBox_3->indexOf(page_7), QApplication::translate("MainWindow", "Ajouter stock", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_6->horizontalHeaderItem(0);
        ___qtablewidgetitem40->setText(QApplication::translate("MainWindow", "numero", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_6->horizontalHeaderItem(1);
        ___qtablewidgetitem41->setText(QApplication::translate("MainWindow", "quantite", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_6->horizontalHeaderItem(2);
        ___qtablewidgetitem42->setText(QApplication::translate("MainWindow", "libelle ", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_6->horizontalHeaderItem(3);
        ___qtablewidgetitem43->setText(QApplication::translate("MainWindow", "Date", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "GroupBox", Q_NULLPTR));
        pushButton_25->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        pushButton_26->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        pushButton_27->setText(QApplication::translate("MainWindow", "Historique", Q_NULLPTR));
        pushButton_28->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        pushButton_29->setText(QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        toolBox_3->setItemText(toolBox_3->indexOf(page_8), QApplication::translate("MainWindow", "afficher stock", Q_NULLPTR));
        toolBox_3->setItemText(toolBox_3->indexOf(page_9), QApplication::translate("MainWindow", "statistiques", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
